[package]
name = "github-dusterthefirst-com"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
dioxus = { version = "0.2.3", features = ["web"] }
reqwest = { version = "0.11.10", features = ["json"] }
serde = { version = "1.0.136", features = ["derive"] }
time = { version = "0.3.9", features = ["serde-well-known"] }
