[package]
name = "github-dusterthefirst-com"
version = "0.0.0"
edition = "2021"
publish = false

[profile.release]
overflow-checks = true

[dependencies]
dioxus = { version = "0.2.3", features = ["web"] }
futures = "0.3.21"
instant = { version = "0.1.12", features = ["wasm-bindgen"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0.79" }
gloo-net = { version = "0.2.0", features = ["http", "json"], default-features = false }
time = { version = "0.3.9", features = ["serde-well-known", "macros"] }
base64 = "0.13.0"
